name: Merge Playwright Reports

description: >
  Consolidates shard test reports and ensures index.html exists for GitHub Pages compatibility.

inputs:
  input-dir:
    description: Directory containing individual shard reports
    required: true
  output-dir:
    description: Output directory for the merged report
    required: true
  artifact-pattern:
    description: Artifact naming pattern (e.g., playwright-report-*)
    required: true

runs:
  using: "composite"
  steps:
    - run: npm ci && npx playwright install --with-deps
      shell: bash

    - run: npm install -D playwright-merge-html-reports
      shell: bash

    - uses: actions/download-artifact@v4
      with:
        path: ${{ inputs.input-dir }}
        pattern: ${{ inputs.artifact-pattern }}
        merge-multiple: true

    - run: |
        npx playwright-merge-html-reports \
          --input ${{ inputs.input-dir }} \
          --output ${{ inputs.output-dir }} \
          --overwrite
      shell: bash

    - run: |
        if [ ! -f ${{ inputs.output-dir }}/index.html ]; then
          echo '<meta http-equiv="refresh" content="0; url=report.html">' > ${{ inputs.output-dir }}/index.html
        fi
      shell: bash
