name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        shard: [1, 2, 3]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (shard ${{ matrix.shard }})
        run: npx playwright test --shard=${{ matrix.shard }}/3
        env:
          CI: true
          TEST_SHARD: ${{ matrix.shard }}

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shard }}
          path: playwright-report/
          retention-days: 7

  merge-playwright-report:
    needs: test
    runs-on: ubuntu-latest
    if: always() && needs.test.result != 'cancelled'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Download all reports
        uses: actions/download-artifact@v4
        with:
          pattern: playwright-report-*
          path: playwright-reports/
          merge-multiple: true

      - name: Install dependencies
        run: npm ci

      - name: Merge Playwright Reports
        run: |
          npx playwright merge-reports --reporter html playwright-reports/
        continue-on-error: true

      - name: Upload merged report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: merged-playwright-report
          path: playwright-report/
          retention-days: 30

  deploy-report:
    needs: merge-playwright-report
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main' && needs.merge-playwright-report.result == 'success'
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Download merged report
        uses: actions/download-artifact@v4
        with:
          name: merged-playwright-report
          path: merged-report

      - name: Create fallback index.html if missing
        run: |
          if [ ! -f merged-report/index.html ]; then
            echo '<html><head><meta http-equiv="refresh" content="0; url=report.html"><title>Playwright Report</title></head><body><p>Redirecting to <a href="report.html">test report</a>...</p></body></html>' > merged-report/index.html
          fi

      - name: Debug merged-report contents
        run: ls -al merged-report || echo "merged-report not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: merged-report/
          keep_files: false