name: Playwright Tests

on:
  schedule:
  - cron: '0 20 * * *'  # 03:00 WIB (20:00 UTC)
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        shard: [1, 2, 3]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (shard ${{ matrix.shard }})
        run: npx playwright test --shard=${{ matrix.shard }}/3
        env:
          CI: true
          TEST_SHARD: ${{ matrix.shard }}

      - name: Upload blob report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shard }}
          path: blob-report/
          retention-days: 7

  merge-playwright-report:
    needs: test
    runs-on: ubuntu-latest
    if: always() && needs.test.result != 'cancelled'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install

      - name: Download all blob reports
        uses: actions/download-artifact@v4
        with:
          pattern: blob-report-*
          path: all-blob-reports/
          merge-multiple: true

      - name: Debug downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -la all-blob-reports/ || echo "No all-blob-reports directory"
          find all-blob-reports/ -name "*.zip" || echo "No zip files found"

      - name: Merge Playwright Reports
        run: |
          if [ -d "all-blob-reports" ] && [ "$(find all-blob-reports -name '*.zip' | wc -l)" -gt 0 ]; then
            echo "Merging reports..."
            npx playwright merge-reports --reporter html all-blob-reports/
          else
            echo "No blob reports to merge, creating empty report"
            mkdir -p playwright-report
            echo '<html><head><title>No Tests Run</title></head><body><h1>No test reports available</h1></body></html>' > playwright-report/index.html
          fi

      - name: Upload merged HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: merged-playwright-report
          path: playwright-report/
          retention-days: 30

  deploy-report:
    needs: [test, merge-playwright-report]
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main' && (needs.merge-playwright-report.result == 'success' || needs.test.result == 'success')
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Download merged report
        uses: actions/download-artifact@v4
        with:
          name: merged-playwright-report
          path: final-report

      - name: Ensure index.html exists
        run: |
          if [ ! -f final-report/index.html ]; then
            # Look for any HTML file to redirect to
            html_file=$(find final-report -name "*.html" | head -1)
            if [ -n "$html_file" ]; then
              basename_html=$(basename "$html_file")
              echo "<html><head><meta http-equiv=\"refresh\" content=\"0; url=$basename_html\"><title>Playwright Report</title></head><body><p>Redirecting to <a href=\"$basename_html\">test report</a>...</p></body></html>" > final-report/index.html
            else
              echo '<html><head><title>No Reports</title></head><body><h1>No HTML reports found</h1></body></html>' > final-report/index.html
            fi
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: final-report/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4